#!/bin/bash
#SBATCH -J kamrul_custom_minibatch
#SBATCH -o ../experiment/attention_model/dummy/custom_minibatch/out/my_output_%j
#SBATCH --mem=32GB
#SBATCH -t 5-00:00:00
#SBATCH -n 1
#SBATCH -c 12
#SBATCH -p gpu
#SBATCH --gres=gpu:1


module load anaconda
module load cuda

python ~/ets/deep_learning/attention_model/train_attention_mosi.py
